version: '3.3'

services:
  graphdb:
    image: docker-registry.ontotext.com/graphdb:${GDB_VERSION}
    environment:
      GDB_JAVA_OPTS: >-
        -Dgraphdb.workbench.importDirectory=/opt/home/import-data/
        -Dgraphdb.jsonld.whitelist=https://w3c.github.io/json-ld-api/tests/*
        -Dgraphdb.stats.default=disabled
        -Dgraphdb.foreground=
        -Dgraphdb.logger.root.level=ERROR
    ports:
      - '7200:7200'
    volumes:
      - ./e2e-tests/fixtures/graphdb-import:/opt/home/import-data/
      - ./e2e-tests/fixtures/graphdb.license:/opt/graphdb/home/conf/graphdb.license
    networks:
      - single-spa-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f -H 'Accept: text/html' ${GRAPHDB_URL}/index.html"]
      interval: 10s
      timeout: 5s
      retries: 5

  workbench:
    build:
      context: .
      dockerfile: workbench.Dockerfile
    environment:
      GRAPHDB_URL: ${GRAPHDB_URL}
      WORKBENCH_PORT: ${WORKBENCH_PORT}
    depends_on:
      - graphdb
    ports:
      - ${WORKBENCH_PORT}
    networks:
      - single-spa-network
    healthcheck:
      test: ["CMD-SHELL", "apk add --no-cache curl && curl -f -H 'Accept: */*' http://workbench:${WORKBENCH_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  cypress:
    image: cypress/included:14.5.1
    depends_on:
      - workbench
    environment:
      - CYPRESS_baseUrl=http://workbench:${WORKBENCH_PORT}
      - COVERAGE=true
      - NO_COLOR=true
    user: "${UID}:${GID}"
    working_dir: /e2e
    volumes:
      - ./e2e-tests:/e2e
      - ${PWD}/packages:${PWD}/packages:cached
    entrypoint: ["npm", "run", "cy:run-legacy:coverage"]
    networks:
      - single-spa-network

networks:
  single-spa-network:
    driver: bridge
