version: '3.2'

services:
    workbench:
        image: node:18-alpine
        working_dir: /app
        ports:
            - "9000:9000"
            - "9002:9002"
            - "9003:9003"
        volumes:
            - ./:/app
        command: npm run start

    cypress:
        image: cypress/included
        depends_on:
            - workbench
        environment:
            - CYPRESS_baseUrl=http://workbench:9000
            - NO_COLOR=true
        working_dir: /e2e
        volumes:
            - ./e2e-tests:/e2e
        command: cypress run --config-file cypress-legacy.config.js
