export enum Authority {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_USER = 'ROLE_USER',
  ROLE_MONITORING = 'ROLE_MONITORING',
  ROLE_REPO_MANAGER = 'ROLE_REPO_MANAGER',
  ROLE_CLUSTER = 'ROLE_CLUSTER',
  IS_AUTHENTICATED_FULLY = 'IS_AUTHENTICATED_FULLY'
}

