PluginRegistry.add('themes', {
    'name': 'onto-original-theme',
    'label': 'security.workbench.settings.theme.onto-original-theme',
    'primary-color-hue': '17',
    'primary-color-saturation': '87.9%',
    'primary-color-lightness': '49%',
    'secondary-color-hue': '207.3',
    'secondary-color-saturation': '100%',
    'secondary-color-lightness': '19.4%',
    'tertiary-color-hue': '174.6',
    'tertiary-color-saturation': '97.7%',
    'tertiary-color-lightness': '33.5%',
    'icon-on-primary-color': 'rgba(255, 255, 255, 0.8)',
    'grey-rgb': '151, 153, 156',
    'grey-color': '#97999C',
    'color-danger-dark': '#bd362f',
    'color-success-dark': '#51a351',
    'color-warning-dark': '#f89406',
    'color-info-dark': '#2f96b4'
});
