version: '3.4'

services:
  shared_components:
    image: node:22-alpine
    working_dir: /app
    user: "${UID}:${GID}"
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - ../api:/api
      - ../root-config:/root-config
    command: npm run start
    healthcheck:
      test: [ "CMD", "sh", "-c", "wget -q -O - http://shared_components:3333/ | grep -q 'Main'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  cypress:
    image: cypress/included:14.5.0
    depends_on:
      shared_components:
        condition: service_healthy
    environment:
      - CYPRESS_baseUrl=http://shared_components:3333
      - NO_COLOR=true
    user: "${UID}:${GID}"
    working_dir: /e2e
    volumes:
      - ./:/e2e
    command: cypress run --browser chrome --config-file cypress.config.js
